server:
  port: 8005

spring:
  application:
    name: auth-api
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/usuarios?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000 # 1h in millisecond
