# Use root/example as user/password credentials
version: '3.1'

services:

  database:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    container_name: database
    hostname: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - taskwork

  prometheus:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - taskwork
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:10.4.7
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - taskwork

  task-manager:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-manager:latest
    container_name: task-manager
    hostname: task-manager
    restart: always
    environment:
      DB_HOST: database
      DB_PORT: 3306
    ports:
      - 8080:8080
    networks:
      - taskwork
    depends_on:
      - database
      - prometheus
      - grafana

networks:
  taskwork:
    driver: bridge

volumes:
  db_data:
  prometheus_data: